In [1]:
!pip install numpy

In [2]:
import numpy as np
print(np.__name__, np.__version__)

numpy 1.19.2


# 1. 基础知识

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([[9.0,10.0,6.0],[6.0,1.0,7.0]])
b

array([[ 9., 10.,  6.],
       [ 6.,  1.,  7.]])

In [5]:
np.array([1,3.0,0.004,-2])

array([ 1.   ,  3.   ,  0.004, -2.   ])

尺寸

In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

查找数组长度

In [10]:
len(a)

3

# 2. 重复

In [11]:
np.array([2,4,6]*4)

array([2, 4, 6, 2, 4, 6, 2, 4, 6, 2, 4, 6])

In [12]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [13]:
arr=np.array([[2,4,6]])
arr

array([[2, 4, 6]])

In [14]:
np.repeat(arr,3,axis=0)

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [15]:
np.repeat(arr,3,axis=1)

array([[2, 2, 2, 4, 4, 4, 6, 6, 6]])

# 3. 数学运算

In [16]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [17]:
a+2

array([3, 4, 5, 6])

In [18]:
a-2

array([-1,  0,  1,  2])

In [19]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [20]:
a**2

array([ 1,  4,  9, 16])

In [21]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [22]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [23]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [24]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [25]:
b=np.array([3,4,5,6])
b

array([3, 4, 5, 6])

In [26]:
a

array([1, 2, 3, 4])

In [27]:
a+b

array([ 4,  6,  8, 10])

In [28]:
a-b

array([-2, -2, -2, -2])

In [29]:
a*b

array([ 3,  8, 15, 24])

In [30]:
a/b

array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [31]:
a**b

array([   1,   16,  243, 4096])

In [32]:
a.dot(b) #1*3+2*4+3*5+4*6

50

In [33]:
np.dot(a,b)

50

In [34]:
# 多维数组使用dot
c=np.array([[3,5,1],[6,4,9]])
c

array([[3, 5, 1],
       [6, 4, 9]])

In [35]:
d=np.array([[5,2],[7,9],[4,3]])
d

array([[5, 2],
       [7, 9],
       [4, 3]])

In [36]:
c.dot(d)

array([[54, 54],
       [94, 75]])

In [37]:
np.matmul(c,d)

array([[54, 54],
       [94, 75]])

# 4. 统计

In [38]:
x=np.array([1,3,4,6,-3,-2])
x.sum()

9

In [39]:
x.max()

6

In [40]:
x.min()

-3

In [41]:
x.mean()

1.5

In [42]:
x.std() # 标准差

3.2015621187164243

In [43]:
x.argmin() # 最小元素索引

4

In [44]:
x.argmax() # 最大元素索引

3

# 5. 初始化不同类型的数组

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(10)**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [47]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [48]:
np.linspace(0,3,15)

array([0.        , 0.21428571, 0.42857143, 0.64285714, 0.85714286,
       1.07142857, 1.28571429, 1.5       , 1.71428571, 1.92857143,
       2.14285714, 2.35714286, 2.57142857, 2.78571429, 3.        ])

In [49]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.ones((4,3,2),dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [52]:
np.full((2,2),30)

array([[30, 30],
       [30, 30]])

In [53]:
ar=np.array([[2,3],[4,5]])
ar

array([[2, 3],
       [4, 5]])

In [54]:
np.full_like(ar,4)

array([[4, 4],
       [4, 4]])

In [55]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [58]:
a=np.array([2,4,5])
np.diag(a)

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

# 6. 重新排列或重新组织数组

In [59]:
x=np.arange(0,45,3)
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [60]:
x.reshape(3,5)

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [61]:
x.resize(3,5)
x

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [62]:
x.ravel()

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [63]:
c=np.array([4,5,6])
c

array([4, 5, 6])

In [64]:
c.resize(3,1)
c

array([[4],
       [5],
       [6]])

In [65]:
c.resize(1,3)
c

array([[4, 5, 6]])

In [66]:
x=np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
x.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [68]:
y=x.reshape(4,-1)
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [69]:
y.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

# 7. 索引或切片

In [70]:
a=np.array([2,5,1,7,6,3,9,0,4])

In [71]:
a[0]

2

In [72]:
a[1:5]

array([5, 1, 7, 6])

# 8. 添加行或列

In [73]:
x1=[[2,4,3,7],[2,5,3,1]]
x2=[1,0,9,5]

In [74]:
np.vstack([x1,x2])

array([[2, 4, 3, 7],
       [2, 5, 3, 1],
       [1, 0, 9, 5]])

In [75]:
np.vstack([x1,x2,x2])

array([[2, 4, 3, 7],
       [2, 5, 3, 1],
       [1, 0, 9, 5],
       [1, 0, 9, 5]])

In [76]:
np.array(x1)

array([[2, 4, 3, 7],
       [2, 5, 3, 1]])

In [77]:
x3=np.ones((2,3))
x3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [78]:
np.hstack([x1,x3])

array([[2., 4., 3., 7., 1., 1., 1.],
       [2., 5., 3., 1., 1., 1., 1.]])

连接

In [79]:
x1=[[2,4,3,7],[2,5,3,1]]
x2=[[1,0,9,5]]

In [80]:
np.concatenate((x1,x2),axis=0)

array([[2, 4, 3, 7],
       [2, 5, 3, 1],
       [1, 0, 9, 5]])

In [81]:
x3=[[2,4],[7,5]]

In [82]:
np.concatenate((x1,x3),axis=1)

array([[2, 4, 3, 7, 2, 4],
       [2, 5, 3, 1, 7, 5]])

# 9. 追加，插入，删除和排序

In [83]:
np.append([2,3],[[4,5],[1,3]])

array([2, 3, 4, 5, 1, 3])

In [84]:
np.append([2,3,1],[[4,5],[1,3]])

array([2, 3, 1, 4, 5, 1, 3])

In [85]:
np.append([[1,3,5],[4,3,6]],[[1,2,3]],axis=0)

array([[1, 3, 5],
       [4, 3, 6],
       [1, 2, 3]])

In [86]:
a=np.array([[2,2],[3,4],[5,6]])
a

array([[2, 2],
       [3, 4],
       [5, 6]])

In [87]:
np.insert(a,0,5) # 数组展平后开头插入5

array([5, 2, 2, 3, 4, 5, 6])

In [88]:
np.insert(a,0,5,axis=1)

array([[5, 2, 2],
       [5, 3, 4],
       [5, 5, 6]])

In [89]:
np.insert(a,0,5,axis=1)

array([[5, 2, 2],
       [5, 3, 4],
       [5, 5, 6]])

In [90]:
np.insert(a,0,5,axis=0)

array([[5, 5],
       [2, 2],
       [3, 4],
       [5, 6]])

In [91]:
a=np.array([[1,3,2,6],[4,1,6,7],[9,10,6,3]])
a

array([[ 1,  3,  2,  6],
       [ 4,  1,  6,  7],
       [ 9, 10,  6,  3]])

In [92]:
np.delete(a,[1,2,5]) # 删除操作也会展平

array([ 1,  6,  4,  6,  7,  9, 10,  6,  3])

In [93]:
a.flatten()

array([ 1,  3,  2,  6,  4,  1,  6,  7,  9, 10,  6,  3])

In [94]:
np.delete(a,1,1) # 删除的(数组，列索引，轴)

array([[1, 2, 6],
       [4, 6, 7],
       [9, 6, 3]])

In [95]:
np.delete(a,1,0)

array([[ 1,  3,  2,  6],
       [ 9, 10,  6,  3]])

Sort

In [96]:
a

array([[ 1,  3,  2,  6],
       [ 4,  1,  6,  7],
       [ 9, 10,  6,  3]])

In [97]:
np.sort(a)

array([[ 1,  2,  3,  6],
       [ 1,  4,  6,  7],
       [ 3,  6,  9, 10]])

In [98]:
np.sort(a,axis=None)

array([ 1,  1,  2,  3,  3,  4,  6,  6,  6,  7,  9, 10])

In [99]:
np.sort(a,axis=0)

array([[ 1,  1,  2,  3],
       [ 4,  3,  6,  6],
       [ 9, 10,  6,  7]])

In [100]:
np.sort(a,axis=1)

array([[ 1,  2,  3,  6],
       [ 1,  4,  6,  7],
       [ 3,  6,  9, 10]])

Flip

In [101]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
np.flip(arr,0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [103]:
np.flip(arr,1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

# 10. 随机

In [104]:
np.random.rand()

0.25492976784873234

In [105]:
np.random.rand(3)

array([0.79625544, 0.98127078, 0.35585376])

In [106]:
np.random.rand(2,3)

array([[3.71848870e-04, 4.41928157e-01, 7.61270454e-01],
       [9.37040983e-01, 8.49487484e-01, 7.99342207e-01]])

In [107]:
np.random.randint(25) # 0-25

2

In [108]:
np.random.randint(1,100,10)

array([ 2, 26, 94, 65, 24, 97, 21,  9, 10, 88])

In [109]:
np.random.randint(1,100,(3,3))

array([[92, 49, 62],
       [ 3, 25, 72],
       [97, 95, 51]])

In [110]:
np.random.choice([1,2,3,4,5,6,7,8,9,10], size=(3,3))

array([[3, 2, 5],
       [3, 8, 3],
       [2, 1, 2]])

In [111]:
a=np.array([3,6,3,1,0,11])
np.random.shuffle(a)
a

array([ 0,  1,  6, 11,  3,  3])

# 11. 保存，加载，导入文件

In [112]:
np.save('arrfile',arr)

In [113]:
np.load('arrfile.npy')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
a=np.array([1,2,3,4,5])
np.savetxt("foo.csv", a, delimiter=",")

In [115]:
filedata=np.genfromtxt('foo.csv',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([1, 2, 3, 4, 5], dtype=int32)

In [116]:
!rm -rf foo.csv arrfile.npy # clean up